# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ledapi_pb2 as ledapi__pb2


class LEDServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsAlive = channel.unary_unary(
                '/LEDService/IsAlive',
                request_serializer=ledapi__pb2.Void.SerializeToString,
                response_deserializer=ledapi__pb2.Success.FromString,
                )
        self.SetColor = channel.unary_unary(
                '/LEDService/SetColor',
                request_serializer=ledapi__pb2.Color.SerializeToString,
                response_deserializer=ledapi__pb2.Success.FromString,
                )


class LEDServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IsAlive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetColor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LEDServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.IsAlive,
                    request_deserializer=ledapi__pb2.Void.FromString,
                    response_serializer=ledapi__pb2.Success.SerializeToString,
            ),
            'SetColor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetColor,
                    request_deserializer=ledapi__pb2.Color.FromString,
                    response_serializer=ledapi__pb2.Success.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LEDService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LEDService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IsAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LEDService/IsAlive',
            ledapi__pb2.Void.SerializeToString,
            ledapi__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetColor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LEDService/SetColor',
            ledapi__pb2.Color.SerializeToString,
            ledapi__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
